// examples/typescript/svelte/vite/src/App.svelte
<script lang="ts">
  import { documentMarkdownReader } from '@interview-challenge-archive/document-markdown-reader';

  let markdown = '';
  let loading = false;
  let error = '';
  let fileInput: HTMLInputElement | undefined;

  const acceptedExtensions = documentMarkdownReader.acceptedExtensions;

  async function handleConvert() {
    const file = fileInput?.files?.[0];
    if (!file) {
      error = 'Please select a file first';
      markdown = '';
      return;
    }

    loading = true;
    error = '';
    markdown = '';

    try {
      markdown = await documentMarkdownReader.readDocument(file);
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to read document';
    } finally {
      loading = false;
    }
  }
</script>

<main class="container">
  <h1>Document Markdown Reader</h1>
  <p>TypeScript + Svelte + Vite example</p>

  <input bind:this={fileInput} type="file" accept={acceptedExtensions} disabled={loading} />
  <button id="convert-btn" type="button" on:click={handleConvert} disabled={loading}>
    Convert to Markdown
  </button>

  <p>{loading ? 'Loading document...' : ''}</p>
  <p class="error">{error}</p>
  <pre id="output">{markdown}</pre>
</main>

<style>
  .container {
    font-family: system-ui, sans-serif;
    max-width: 800px;
    margin: 2rem auto;
    padding: 0 1rem;
  }

  button {
    margin-left: 0.5rem;
  }

  .error {
    color: #b00020;
  }

  pre {
    white-space: pre-wrap;
    background: #f5f5f5;
    padding: 1rem;
  }
</style>

// examples/typescript/vue/webpack/src/App.vue
<template>
  <div class="app">
    <h1>Document Markdown Reader</h1>
    <p>TypeScript + Vue + Webpack example</p>

    <div>
      <input
        ref="fileInputRef"
        type="file"
        :accept="acceptedExtensions"
        :disabled="loading"
      />
      <button type="button" id="convert-btn" @click="handleConvert" :disabled="loading">
        Convert to Markdown
      </button>
    </div>

    <p id="loading">{{ loading ? 'Loading document...' : '' }}</p>
    <p v-if="error" id="error" class="error">{{ error }}</p>
    <pre id="output">{{ content }}</pre>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { documentMarkdownReader } from '@interview-challenge-archive/document-markdown-reader';

const content = ref('');
const loading = ref(false);
const error = ref('');
const fileInputRef = ref<HTMLInputElement | null>(null);
const acceptedExtensions = documentMarkdownReader.acceptedExtensions;

const handleConvert = async () => {
  const file = fileInputRef.value?.files?.[0];
  if (!file) {
    error.value = 'Please select a file first';
    content.value = '';
    return;
  }

  loading.value = true;
  error.value = '';
  content.value = '';

  try {
    content.value = await documentMarkdownReader.readDocument(file);
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to read document';
  } finally {
    loading.value = false;
  }
};
</script>

<style>
.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  font-size: 1.5rem;
}

input[type="file"] {
  margin-bottom: 1rem;
}

.error {
  color: red;
}

pre {
  white-space: pre-wrap;
  background: #f5f5f5;
  padding: 1rem;
}
</style>
