// examples/typescript/react/webpack/src/App.tsx
import React, { useRef, useState } from 'react';
import { documentMarkdownReader } from '@interview-challenge-archive/document-markdown-reader';
import './App.css';

function App() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [markdown, setMarkdown] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  async function handleConvert() {
    const selectedFile = fileInputRef.current?.files?.[0];
    if (!selectedFile) {
      setError('Please select a file first');
      setMarkdown('');
      return;
    }

    setIsLoading(true);
    setError('');
    setMarkdown('');

    try {
      setMarkdown(await documentMarkdownReader.readDocument(selectedFile));
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to read document');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="container">
      <h1>Document Reader - React + TypeScript + Webpack</h1>

      <div className="upload-section">
        <input ref={fileInputRef} type="file" accept={documentMarkdownReader.acceptedExtensions} />
        <button id="convert-btn" type="button" onClick={handleConvert} disabled={isLoading}>
          Convert to Markdown
        </button>
      </div>

      {isLoading && <div className="loading">Loading document...</div>}

      {error && <div className="error">{error}</div>}

      {markdown && (
        <div className="result">
          <h2>Markdown Output:</h2>
          <pre id="output">{markdown}</pre>
        </div>
      )}
    </div>
  );
}

export default App;

// examples/typescript/solidjs/webpack/src/App.tsx
import { createSignal } from 'solid-js';
import { documentMarkdownReader } from '@interview-challenge-archive/document-markdown-reader';
import './App.css';

function App() {
  let fileInputRef: HTMLInputElement | undefined;
  const [markdown, setMarkdown] = createSignal('');
  const [isLoading, setIsLoading] = createSignal(false);
  const [error, setError] = createSignal('');

  async function handleConvert() {
    const selectedFile = fileInputRef?.files?.[0];
    if (!selectedFile) {
      setError('Please select a file first');
      setMarkdown('');
      return;
    }

    setIsLoading(true);
    setError('');
    setMarkdown('');

    try {
      setMarkdown(await documentMarkdownReader.readDocument(selectedFile));
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to read document');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div class="container">
      <h1>Document Reader - SolidJS + TypeScript + Webpack</h1>

      <div class="upload-section">
        <input ref={fileInputRef} type="file" accept={documentMarkdownReader.acceptedExtensions} />
        <button id="convert-btn" type="button" onClick={handleConvert} disabled={isLoading()}>
          Convert to Markdown
        </button>
      </div>

      {isLoading() && <div class="loading">Loading document...</div>}

      {error() && <div class="error">{error()}</div>}

      {markdown() && (
        <div class="result">
          <h2>Markdown Output:</h2>
          <pre>{markdown()}</pre>
        </div>
      )}
    </div>
  );
}

export default App;
