// examples/javascript/react/vite/src/App.jsx
import { useState } from 'react';
import { DocumentMarkdownReader } from 'document-markdown-reader';

function App() {
  const [markdown, setMarkdown] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleFileChange = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setLoading(true);
    setError('');
    setMarkdown('');

    try {
      const reader = new DocumentMarkdownReader();
      const result = await reader.read(file);
      setMarkdown(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to read document');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="app">
      <h1>Document to Markdown Converter</h1>
      <p>Select a document file to convert to Markdown:</p>
      <input type="file" onChange={handleFileChange} disabled={loading} />
      {loading && <p>Loading...</p>}
      {error && <p className="error">{error}</p>}
      {markdown && (
        <div>
          <h2>Result:</h2>
          <pre>{markdown}</pre>
        </div>
      )}
    </div>
  );
}

export default App;

// examples/javascript/vue/rollup/src/App.vue
<template>
  <div class="app">
    <h1>Document to Markdown Converter</h1>
    <p>Select a document file to convert to Markdown:</p>
    <input type="file" @change="handleFileChange" :disabled="loading" />
    <p v-if="loading">Loading...</p>
    <p v-if="error" class="error">{{ error }}</p>
    <div v-if="markdown">
      <h2>Result:</h2>
      <pre>{{ markdown }}</pre>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { DocumentMarkdownReader } from 'document-markdown-reader';

const markdown = ref('');
const error = ref('');
const loading = ref(false);

const handleFileChange = async (event) => {
  const file = event.target.files?.[0];
  if (!file) return;

  loading.value = true;
  error.value = '';
  markdown.value = '';

  try {
    const reader = new DocumentMarkdownReader();
    const result = await reader.read(file);
    markdown.value = result;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to read document';
  } finally {
    loading.value = false;
  }
};
</script>

<style>
.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  font-size: 1.5rem;
}

input[type="file"] {
  margin-bottom: 1rem;
}

.error {
  color: red;
}

pre {
  white-space: pre-wrap;
  background: #f5f5f5;
  padding: 1rem;
}
</style>
