// examples/typescript/vue/parcel/src/App.vue
<template>
  <div class="app">
    <h1>Document Markdown Reader</h1>
    <p>TypeScript + Vue + Parcel example</p>

    <div>
      <input
        type="file"
        accept=".pdf,.docx,.odt,.pages,.html,.md,.txt,.rtf"
        @change="handleFileChange"
        :disabled="loading"
      />
    </div>

    <p v-if="loading">Loading document...</p>
    <p v-if="error" class="error">{{ error }}</p>

    <div v-if="content">
      <h2>Content:</h2>
      <pre>{{ content }}</pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DocumentMarkdownReader } from 'document-markdown-reader';

const content = ref('');
const loading = ref(false);
const error = ref('');

const handleFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  loading.value = true;
  error.value = '';
  content.value = '';

  try {
    const reader = new DocumentMarkdownReader();
    const markdown = await reader.read(file);
    content.value = markdown;
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to read document';
  } finally {
    loading.value = false;
  }
};
</script>

<style>
.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  font-size: 1.5rem;
}

input[type="file"] {
  margin-bottom: 1rem;
}

.error {
  color: red;
}

pre {
  white-space: pre-wrap;
  background: #f5f5f5;
  padding: 1rem;
}
</style>

// examples/typescript/solidjs/rollup/src/App.tsx
import { createSignal } from 'solid-js';
import { DocumentMarkdownReader } from 'document-markdown-reader';

function App() {
  const [content, setContent] = createSignal<string>('');
  const [isLoading, setIsLoading] = createSignal<boolean>(false);
  const [error, setError] = createSignal<string>('');

  const handleFileChange = async (event: Event) => {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];

    if (!file) {
      return;
    }

    setIsLoading(true);
    setError('');
    setContent('');

    try {
      const reader = new DocumentMarkdownReader();
      const markdown = await reader.read(file);
      setContent(markdown);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to read document');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{ padding: '20px', 'font-family': 'system-ui, sans-serif' }}>
      <h1>Document Markdown Reader - SolidJS</h1>

      <div style={{ 'margin-bottom': '20px' }}>
        <input
          type="file"
          accept=".pdf,.docx,.odt,.pages,.rtf,.html,.md,.txt"
          onChange={handleFileChange}
          style={{ 'font-size': '16px' }}
        />
      </div>

      {isLoading() && <p>Loading...</p>}

      {error() && (
        <p style={{ color: 'red' }}>{error()}</p>
      )}

      {content() && (
        <div>
          <h2>Content:</h2>
          <pre style={{ background: '#f5f5f5', padding: '10px', 'white-space': 'pre-wrap' }}>
            {content()}
          </pre>
        </div>
      )}
    </div>
  );
}

export default App;
